[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs-18", "npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public" 